#!/usr/bin/env bats
# Adversarial QA gaps for FEAT-029 — covers P0/P1 scenarios in
# qa/test-plans/QA-plan-FEAT-029.md not exercised by the existing bats
# suites. Generated by executing-qa run for FEAT-029.

setup() {
  SCRIPT_DIR="$(cd "${BATS_TEST_DIRNAME}/.." && pwd)"
  BUDGET="${SCRIPT_DIR}/phase-complexity-budget.sh"
  RENDER="${SCRIPT_DIR}/render-plan-scaffold.sh"
  VALIDATE_DAG="${SCRIPT_DIR}/validate-plan-dag.sh"
  VALIDATE_SIZES="${SCRIPT_DIR}/validate-phase-sizes.sh"
  SPLIT="${SCRIPT_DIR}/split-phase-suggest.sh"
  FIXTURES="${BATS_TEST_DIRNAME}/fixtures"
  WORK_DIR="$(mktemp -d)"
}

teardown() {
  if [ -n "${WORK_DIR:-}" ] && [ -d "$WORK_DIR" ]; then
    rm -rf "$WORK_DIR"
  fi
}

# Synthesize a plan with N phases, each with `steps` Implementation Steps
# and `delivs` Deliverable entries. extra_body is appended once into Phase 1
# only. Override applies to Phase 1 only.
make_plan_n_phases() {
  local out="$1"
  local n="$2"
  local steps="$3"
  local delivs="$4"
  local body="${5:-}"
  local override="${6:-}"
  : > "$out"
  printf '# Plan\n\n## Build Sequence\n\n' >> "$out"
  local p=1
  while [ "$p" -le "$n" ]; do
    printf '### Phase %d: P%d\n\n' "$p" "$p" >> "$out"
    printf '**Status:** Pending\n' >> "$out"
    if [ "$p" -eq 1 ] && [ -n "$override" ]; then
      printf '**ComplexityOverride:** %s\n' "$override" >> "$out"
    fi
    if [ "$p" -eq 1 ] && [ -n "$body" ]; then
      printf '\n%s\n' "$body" >> "$out"
    fi
    printf '\n#### Implementation Steps\n\n' >> "$out"
    local i=1
    while [ "$i" -le "$steps" ]; do
      printf '%d. Step %d.\n' "$i" "$i" >> "$out"
      i=$((i + 1))
    done
    printf '\n#### Deliverables\n\n' >> "$out"
    i=1
    while [ "$i" -le "$delivs" ]; do
      printf -- '- [ ] `p%d-%d.sh`\n' "$p" "$i" >> "$out"
      i=$((i + 1))
    done
    printf '\n---\n\n' >> "$out"
    p=$((p + 1))
  done
}

# JSON tier extraction helper (jq when available, regex fallback otherwise).
tier_of() {
  local json="$1"
  if command -v jq >/dev/null 2>&1; then
    printf '%s' "$json" | jq -r '.tier'
  else
    printf '%s' "$json" | sed -n 's/.*"tier":"\([^"]*\)".*/\1/p'
  fi
}

# ---------------------------------------------------------------------------
# Inputs gaps: phase index range/format
# ---------------------------------------------------------------------------

@test "phase-complexity-budget: --phase 0 (out-of-range low) exits 2" {
  run bash "$BUDGET" "${FIXTURES}/budget-mixed-plan.md" --phase 0
  [ "$status" -eq 2 ]
  echo "$output" | grep -q 'positive integer'
}

@test "phase-complexity-budget: --phase -1 (negative) exits 2" {
  run bash "$BUDGET" "${FIXTURES}/budget-mixed-plan.md" --phase -1
  # bash arg parsing: --phase consumes "-1" as value; regex rejects.
  [ "$status" -eq 2 ]
  echo "$output" | grep -Eq 'positive integer|unknown flag'
}

@test "phase-complexity-budget: --phase 1.5 (non-integer) exits 2" {
  run bash "$BUDGET" "${FIXTURES}/budget-mixed-plan.md" --phase 1.5
  [ "$status" -eq 2 ]
  echo "$output" | grep -q 'positive integer'
}

@test "phase-complexity-budget: --phase 99 on a 3-phase plan exits 1" {
  local f="${WORK_DIR}/three.md"
  make_plan_n_phases "$f" 3 1 1
  run bash "$BUDGET" "$f" --phase 99
  [ "$status" -eq 1 ]
  # script's not-found message: "phase block missing" or similar
  [ -n "$output" ]
}

# ---------------------------------------------------------------------------
# Inputs gaps: ComplexityOverride values
# ---------------------------------------------------------------------------

@test "override invalid_tier (garbage): falls back / does not crash" {
  local f="${WORK_DIR}/override-garbage.md"
  make_plan_n_phases "$f" 1 1 1 '' 'invalid_tier'
  run bash "$BUDGET" "$f" --phase 1
  # Documented behavior: invalid override values are not accepted as a
  # valid tier — script must not crash. Either exits non-zero with a
  # diagnostic, OR exits 0 with override=null (silently ignored). Assert
  # one of those two well-defined shapes; capture which for the report.
  if [ "$status" -eq 0 ]; then
    # Silent-ignore path: override field must NOT be the garbage value.
    if command -v jq >/dev/null 2>&1; then
      ov="$(printf '%s' "$output" | jq -r '.override')"
      [ "$ov" != "invalid_tier" ]
    fi
  else
    [ "$status" -ne 0 ]
  fi
}

@test "override empty value (no token after colon): does not crash" {
  local f="${WORK_DIR}/override-empty.md"
  : > "$f"
  printf '# Plan\n\n### Phase 1: P1\n\n**Status:** Pending\n**ComplexityOverride:**\n\n' >> "$f"
  printf '#### Implementation Steps\n\n1. Step.\n\n#### Deliverables\n\n- [ ] `a.sh`\n' >> "$f"
  run bash "$BUDGET" "$f" --phase 1
  # Either exit 0 with no/null override, or exit non-zero with diagnostic.
  if [ "$status" -eq 0 ]; then
    if command -v jq >/dev/null 2>&1; then
      ov="$(printf '%s' "$output" | jq -r '.override')"
      [ "$ov" = "null" ] || [ -z "$ov" ]
    fi
  fi
}

@test "override HAIKU (uppercase): rejected with diagnostic" {
  local f="${WORK_DIR}/override-upper.md"
  make_plan_n_phases "$f" 1 9 1 '' 'HAIKU'
  run bash "$BUDGET" "$f" --phase 1
  # Behavior: lowercase-only override; uppercase rejected with exit 1 and
  # actionable diagnostic listing the allowed values.
  [ "$status" -eq 1 ]
  echo "$output" | grep -q 'invalid \*\*ComplexityOverride:\*\* value: HAIKU'
  echo "$output" | grep -q 'allowed: haiku, sonnet, opus'
}

# ---------------------------------------------------------------------------
# Inputs gaps: heuristic flag case-insensitive matching
# ---------------------------------------------------------------------------

@test "heuristic low-flag uppercase 'SCHEMA' matches (case-insensitive)" {
  local f="${WORK_DIR}/flag-upper.md"
  # 4 steps -> sonnet base; SCHEMA (low flag) bumps to opus.
  make_plan_n_phases "$f" 1 4 1 'This phase touches SCHEMA migrations.'
  run bash "$BUDGET" "$f" --phase 1
  [ "$status" -eq 0 ]
  [ "$(tier_of "$output")" = "opus" ]
}

@test "heuristic low-flag mixed-case 'Schema' matches (case-insensitive)" {
  local f="${WORK_DIR}/flag-mixed.md"
  make_plan_n_phases "$f" 1 4 1 'Phase touches Schema work.'
  run bash "$BUDGET" "$f" --phase 1
  [ "$status" -eq 0 ]
  [ "$(tier_of "$output")" = "opus" ]
}

@test "heuristic flag inside fenced block does NOT match (fence-aware)" {
  local f="${WORK_DIR}/flag-fenced.md"
  : > "$f"
  cat > "$f" <<'EOF'
# Plan

### Phase 1: Fenced Flag Demo

**Status:** Pending

```
This phase mentions schema only inside a fence.
```

#### Implementation Steps

1. One.
2. Two.
3. Three.
4. Four.

#### Deliverables

- [ ] `a.sh`
EOF
  run bash "$BUDGET" "$f" --phase 1
  [ "$status" -eq 0 ]
  # 4 steps -> sonnet base; flag inside fence must NOT bump.
  [ "$(tier_of "$output")" = "sonnet" ]
}

# ---------------------------------------------------------------------------
# Dependency-failure gap: validate-phase-sizes.sh propagates upstream failure
# ---------------------------------------------------------------------------

@test "validate-phase-sizes propagates exit 1 from non-existent plan" {
  run bash "$VALIDATE_SIZES" "${WORK_DIR}/does-not-exist.md"
  [ "$status" -eq 1 ]
  echo "$output" | grep -q 'plan file not found'
}

@test "validate-phase-sizes propagates exit 1 from plan with no phase blocks" {
  local f="${WORK_DIR}/no-phases.md"
  printf '# Plan\n\nJust prose, no phase blocks.\n' > "$f"
  run bash "$VALIDATE_SIZES" "$f"
  [ "$status" -eq 1 ]
}

# ---------------------------------------------------------------------------
# State-transition gap: 1-phase opus plan resolves to high (FEAT-029
# correctly treats 1-phase plan by per-phase tier, not raw count)
# ---------------------------------------------------------------------------

@test "1-phase opus plan: phase tier is opus (max-of-per-phase semantics)" {
  local f="${WORK_DIR}/one-opus.md"
  make_plan_n_phases "$f" 1 9 9
  run bash "$BUDGET" "$f"
  [ "$status" -eq 0 ]
  if command -v jq >/dev/null 2>&1; then
    n="$(printf '%s' "$output" | jq -r 'length')"
    [ "$n" -eq 1 ]
    t="$(printf '%s' "$output" | jq -r '.[0].tier')"
    [ "$t" = "opus" ]
  fi
}

# ---------------------------------------------------------------------------
# Edge Case 8 fix verification: a 3-phase plan with per-phase tiers
# [haiku, sonnet, haiku] vs the equivalent 4-phase plan [haiku, sonnet,
# haiku, haiku] — both must aggregate to the same max tier (sonnet).
# ---------------------------------------------------------------------------

@test "edge case 8: 3-phase vs 4-phase with same max-tier produce same max" {
  # Construct two plans with different phase counts but same per-phase tiers.
  local three="${WORK_DIR}/three-phase.md"
  : > "$three"
  printf '# Plan\n\n## Build\n\n' >> "$three"
  printf '### Phase 1: A\n\n**Status:** Pending\n\n' >> "$three"
  printf '#### Implementation Steps\n\n1. one.\n\n#### Deliverables\n\n- [ ] `a.sh`\n\n---\n\n' >> "$three"
  printf '### Phase 2: B\n\n**Status:** Pending\n\n' >> "$three"
  printf '#### Implementation Steps\n\n1. one.\n2. two.\n3. three.\n4. four.\n\n#### Deliverables\n\n- [ ] `b.sh`\n\n---\n\n' >> "$three"
  printf '### Phase 3: C\n\n**Status:** Pending\n\n' >> "$three"
  printf '#### Implementation Steps\n\n1. one.\n\n#### Deliverables\n\n- [ ] `c.sh`\n' >> "$three"

  local four="${WORK_DIR}/four-phase.md"
  : > "$four"
  printf '# Plan\n\n## Build\n\n' >> "$four"
  printf '### Phase 1: A\n\n**Status:** Pending\n\n' >> "$four"
  printf '#### Implementation Steps\n\n1. one.\n\n#### Deliverables\n\n- [ ] `a.sh`\n\n---\n\n' >> "$four"
  printf '### Phase 2: B\n\n**Status:** Pending\n\n' >> "$four"
  printf '#### Implementation Steps\n\n1. one.\n2. two.\n3. three.\n4. four.\n\n#### Deliverables\n\n- [ ] `b.sh`\n\n---\n\n' >> "$four"
  printf '### Phase 3: C\n\n**Status:** Pending\n\n' >> "$four"
  printf '#### Implementation Steps\n\n1. one.\n\n#### Deliverables\n\n- [ ] `c.sh`\n\n---\n\n' >> "$four"
  printf '### Phase 4: D\n\n**Status:** Pending\n\n' >> "$four"
  printf '#### Implementation Steps\n\n1. one.\n\n#### Deliverables\n\n- [ ] `d.sh`\n' >> "$four"

  run bash "$BUDGET" "$three"
  [ "$status" -eq 0 ]
  three_out="$output"

  run bash "$BUDGET" "$four"
  [ "$status" -eq 0 ]
  four_out="$output"

  if command -v jq >/dev/null 2>&1; then
    three_max="$(printf '%s' "$three_out" | jq -r '[.[].tier] | unique | sort_by(if .=="haiku" then 0 elif .=="sonnet" then 1 else 2 end) | last')"
    four_max="$(printf '%s' "$four_out" | jq -r '[.[].tier] | unique | sort_by(if .=="haiku" then 0 elif .=="sonnet" then 1 else 2 end) | last')"
    [ "$three_max" = "$four_max" ]
  fi
}

# ---------------------------------------------------------------------------
# DAG validator gaps
# ---------------------------------------------------------------------------

@test "validate-plan-dag: '**Depends on:** none' literal treated as no deps" {
  # Already implicit in fixtures/dag-valid-plan.md (Phase 1 uses 'none').
  # Explicit single-phase plan with the literal:
  local f="${WORK_DIR}/dag-none.md"
  cat > "$f" <<'EOF'
# Plan

### Phase 1: Solo

**Status:** Pending
**Depends on:** none

#### Implementation Steps

1. One.

#### Deliverables

- [ ] `solo.sh`
EOF
  run bash "$VALIDATE_DAG" "$f"
  [ "$status" -eq 0 ]
  echo "$output" | grep -q '^ok'
}

@test "validate-plan-dag: '**Depends on:** Phase  1' (double space) parses as Phase 1" {
  local f="${WORK_DIR}/dag-double-space.md"
  cat > "$f" <<'EOF'
# Plan

### Phase 1: First

**Status:** Pending

#### Implementation Steps

1. One.

#### Deliverables

- [ ] `one.sh`

---

### Phase 2: Second

**Status:** Pending
**Depends on:** Phase  1

#### Implementation Steps

1. One.

#### Deliverables

- [ ] `two.sh`
EOF
  run bash "$VALIDATE_DAG" "$f"
  # Either parses correctly (exit 0, ok) or surfaces a clear diagnostic.
  # The contract from QA-plan-FEAT-029.md is "parses Phase 1".
  [ "$status" -eq 0 ]
}
