// Adversarial QA gaps for FEAT-029 — covers vitest-level P0/P1 scenarios
// in qa/test-plans/QA-plan-FEAT-029.md not exercised by the existing
// workflow-state.test.ts suite. Generated by executing-qa run for FEAT-029.

import { describe, it, expect, beforeEach, afterEach } from 'vitest';
import { execSync, spawnSync } from 'node:child_process';
import { mkdtempSync, rmSync, mkdirSync, writeFileSync, readFileSync } from 'node:fs';
import { join } from 'node:path';
import { tmpdir } from 'node:os';

const SCRIPT = join(
  process.cwd(),
  'plugins/lwndev-sdlc/skills/orchestrating-workflows/scripts/workflow-state.sh'
);

const BUDGET_MIXED_PLAN = join(
  process.cwd(),
  'plugins/lwndev-sdlc/skills/creating-implementation-plans/scripts/tests/fixtures/budget-mixed-plan.md'
);

const FEATURE_LOW_1PHASE = join(
  process.cwd(),
  'scripts/__tests__/fixtures/feat-014/feature-low-plan-1phase.md'
);

let testDir: string;

function run(args: string): string {
  return execSync(`bash "${SCRIPT}" ${args}`, {
    cwd: testDir,
    encoding: 'utf-8',
    stdio: ['pipe', 'pipe', 'pipe'],
    env: { ...process.env, PATH: process.env.PATH },
  }).trim();
}

function runJSON(args: string): Record<string, unknown> {
  return JSON.parse(run(args));
}

function runCapture(args: string): { stdout: string; stderr: string; status: number } {
  const result = spawnSync('bash', [SCRIPT, ...args.split(' ').filter(Boolean)], {
    cwd: testDir,
    encoding: 'utf-8',
    env: { ...process.env, PATH: process.env.PATH },
  });
  return {
    stdout: result.stdout ?? '',
    stderr: result.stderr ?? '',
    status: result.status ?? 1,
  };
}

function readState(id: string): Record<string, unknown> {
  return JSON.parse(readFileSync(join(testDir, '.sdlc/workflows', `${id}.json`), 'utf-8'));
}

beforeEach(() => {
  testDir = mkdtempSync(join(tmpdir(), 'qa029-'));
  mkdirSync(join(testDir, '.sdlc/workflows'), { recursive: true });
});

afterEach(() => {
  if (testDir) {
    rmSync(testDir, { recursive: true, force: true });
  }
});

describe('FEAT-029 adversarial gaps', () => {
  describe('classify-post-plan idempotency (Inputs P0 gap)', () => {
    it('invoked twice on the same workflow: second invocation is a no-op (no duplicate audit line)', () => {
      runJSON('init FEAT-501 feature');
      runJSON('set-complexity FEAT-501 medium');

      // First invocation: real upgrade medium -> high, audit line emitted.
      const first = runCapture(`classify-post-plan FEAT-501 ${BUDGET_MIXED_PLAN}`);
      expect(first.status).toBe(0);
      expect(first.stdout.trim()).toBe('high');
      expect(first.stderr).toContain(
        '[model] Work-item complexity upgraded since last invocation: medium → high'
      );
      const stateAfterFirst = readState('FEAT-501');
      expect(stateAfterFirst.complexity).toBe('high');
      expect(stateAfterFirst.complexityStage).toBe('post-plan');

      // Second invocation on same plan: must NOT re-emit the upgrade audit
      // line (persisted is already high; max(persisted, new) is a no-op).
      const second = runCapture(`classify-post-plan FEAT-501 ${BUDGET_MIXED_PLAN}`);
      expect(second.status).toBe(0);
      expect(second.stdout.trim()).toBe('high');
      expect(second.stderr).not.toContain('Work-item complexity upgraded');

      // State unchanged on second invocation.
      const stateAfterSecond = readState('FEAT-501');
      expect(stateAfterSecond.complexity).toBe('high');
      expect(stateAfterSecond.complexityStage).toBe('post-plan');
    });
  });

  describe('Edge Case 8 fix: phase-splitting invariant (Cross-cutting P0 gap)', () => {
    it('splitting a phase preserves max-of-per-phase workflow complexity', () => {
      // Plan A: 3 phases, one of which scores opus -> workflow=high
      // Plan B: 4 phases, same per-phase tiers as A (one opus phase split
      // into two haiku phases) -> workflow=high (NOT promoted to higher
      // tier just because the phase count grew).
      // Under raw-count mapping (pre-FEAT-029) Plan B would have promoted
      // to a different bucket. Under FEAT-029 max-of-tiers it must NOT.

      const planA = join(testDir, 'planA.md');
      const planB = join(testDir, 'planB.md');

      // Plan A: phases [haiku, haiku, opus]
      writeFileSync(
        planA,
        [
          '# Plan A',
          '',
          '### Phase 1: A1',
          '**Status:** Pending',
          '#### Implementation Steps',
          '1. one.',
          '#### Deliverables',
          '- [ ] `a1.sh`',
          '',
          '---',
          '',
          '### Phase 2: A2',
          '**Status:** Pending',
          '#### Implementation Steps',
          '1. one.',
          '#### Deliverables',
          '- [ ] `a2.sh`',
          '',
          '---',
          '',
          '### Phase 3: A3-opus',
          '**Status:** Pending',
          '#### Implementation Steps',
          ...Array.from({ length: 9 }, (_, i) => `${i + 1}. step ${i + 1}.`),
          '',
          '#### Deliverables',
          ...Array.from({ length: 10 }, (_, i) => `- [ ] \`a3-${i + 1}.sh\``),
          '',
        ].join('\n')
      );

      // Plan B: phases [haiku, haiku, haiku, opus] — opus phase preserved,
      // an extra haiku phase prepended. Same max => same workflow tier.
      writeFileSync(
        planB,
        [
          '# Plan B',
          '',
          '### Phase 1: B1',
          '**Status:** Pending',
          '#### Implementation Steps',
          '1. one.',
          '#### Deliverables',
          '- [ ] `b1.sh`',
          '',
          '---',
          '',
          '### Phase 2: B2',
          '**Status:** Pending',
          '#### Implementation Steps',
          '1. one.',
          '#### Deliverables',
          '- [ ] `b2.sh`',
          '',
          '---',
          '',
          '### Phase 3: B3',
          '**Status:** Pending',
          '#### Implementation Steps',
          '1. one.',
          '#### Deliverables',
          '- [ ] `b3.sh`',
          '',
          '---',
          '',
          '### Phase 4: B4-opus',
          '**Status:** Pending',
          '#### Implementation Steps',
          ...Array.from({ length: 9 }, (_, i) => `${i + 1}. step ${i + 1}.`),
          '',
          '#### Deliverables',
          ...Array.from({ length: 10 }, (_, i) => `- [ ] \`b4-${i + 1}.sh\``),
          '',
        ].join('\n')
      );

      // Run classify-post-plan against both starting from the same init.
      runJSON('init FEAT-506 feature');
      runJSON('set-complexity FEAT-506 low');
      const tierA = run(`classify-post-plan FEAT-506 ${planA}`);

      runJSON('init FEAT-507 feature');
      runJSON('set-complexity FEAT-507 low');
      const tierB = run(`classify-post-plan FEAT-507 ${planB}`);

      expect(tierA).toBe(tierB);
      expect(tierA).toBe('high');
    });
  });

  describe('classify-post-plan audit trail completeness (Cross-cutting P0 gap)', () => {
    it('every classify-post-plan upgrade emits exactly one audit line; no-op invocations emit none', () => {
      // Three sequential invocations on increasing-complexity plans.
      // Audit line count should equal the number of real upgrades, not the
      // total invocation count.
      runJSON('init FEAT-503 feature');
      runJSON('set-complexity FEAT-503 low');

      // Invocation 1: low -> medium (using a single-phase plan that scores
      // higher than the persisted low). Use BUDGET_MIXED which scores high.
      const cap1 = runCapture(`classify-post-plan FEAT-503 ${BUDGET_MIXED_PLAN}`);
      const audit1 = (cap1.stderr.match(/Work-item complexity upgraded/g) || []).length;
      expect(audit1).toBe(1);

      // Invocation 2: same plan, persisted now high → no-op, no audit line.
      const cap2 = runCapture(`classify-post-plan FEAT-503 ${BUDGET_MIXED_PLAN}`);
      const audit2 = (cap2.stderr.match(/Work-item complexity upgraded/g) || []).length;
      expect(audit2).toBe(0);

      // Invocation 3: low-scoring plan (1 phase haiku); persisted high; no
      // downgrade per FR-2b upgrade-only invariant; no audit line.
      const cap3 = runCapture(`classify-post-plan FEAT-503 ${FEATURE_LOW_1PHASE}`);
      const audit3 = (cap3.stderr.match(/Work-item complexity upgraded/g) || []).length;
      expect(audit3).toBe(0);

      // Final state must remain high (upgrade-only).
      const state = readState('FEAT-503');
      expect(state.complexity).toBe('high');
    });
  });

  describe('classify-post-plan with malformed phase-budget output (Dependency-failure P0 gap)', () => {
    it('plan with no phase blocks → warn + preserve persisted + exit 0', () => {
      // A plan file that is parseable but contains no phase blocks. The
      // budget script exits 1 ("no `### Phase` blocks"), and the wrapper
      // must degrade gracefully rather than propagate a parse error.
      const emptyPlan = join(testDir, 'empty-plan.md');
      writeFileSync(emptyPlan, '# Implementation Plan\n\nJust prose, no phase blocks.\n');

      runJSON('init FEAT-504 feature');
      runJSON('set-complexity FEAT-504 high');

      const cap = runCapture(`classify-post-plan FEAT-504 ${emptyPlan}`);
      expect(cap.status).toBe(0);
      expect(cap.stdout.trim()).toBe('high');
      expect(cap.stderr).toContain(
        '[warn] classify-post-plan: phase-complexity-budget failed; preserving init-stage complexity high.'
      );
      // State unchanged.
      const state = readState('FEAT-504');
      expect(state.complexity).toBe('high');
      expect(state.complexityStage).toBe('init');
    });
  });

  describe('Single-phase sonnet plan → medium (State-transitions P0 gap)', () => {
    it('a 1-phase plan that scores sonnet aggregates to workflow medium (not auto-low by raw count)', () => {
      // Pre-FEAT-029, a 1-phase plan was always classified as low by raw
      // count. FEAT-029 replaces that with max-of-per-phase, so a 1-phase
      // sonnet plan must aggregate to medium.
      const sonnetPlan = join(testDir, 'sonnet-1phase.md');
      writeFileSync(
        sonnetPlan,
        [
          '# Sonnet 1-phase',
          '',
          '### Phase 1: Solo Sonnet',
          '**Status:** Pending',
          '',
          '#### Implementation Steps',
          ...Array.from({ length: 4 }, (_, i) => `${i + 1}. step.`),
          '',
          '#### Deliverables',
          '- [ ] `a.sh`',
          '',
        ].join('\n')
      );

      runJSON('init FEAT-505 feature');
      runJSON('set-complexity FEAT-505 low');
      expect(run(`classify-post-plan FEAT-505 ${sonnetPlan}`)).toBe('medium');
    });
  });
});
